cmake_minimum_required(VERSION 3.10.0)
project(145watch LANGUAGES CXX VERSION 1.5.0)
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_EXTENSIONS off)
if (MSVC)
    add_compile_options(/W3)
else()
    add_compile_options(-Wall -Wextra -Wpedantic)
endif()
find_package(ftxui CONFIG REQUIRED)
add_executable(${PROJECT_NAME} main.cpp .clang-format README.md vcpkg.json)
target_compile_definitions(${PROJECT_NAME} PRIVATE
    WATCH_PROJECT_VERSION="${PROJECT_VERSION}"
)
target_link_libraries(${PROJECT_NAME} PRIVATE ftxui::dom ftxui::component ftxui::screen)
if(WIN32)
    target_link_libraries(${PROJECT_NAME} PRIVATE winmm)
endif()