cmake_minimum_required(VERSION 3.10.0)
project(145watch LANGUAGES CXX VERSION 1.4)
set(CMAKE_CXX_STANDARD 26)
set(CMAKE_CXX_EXTENSIONS off)
if (MSVC)
    add_compile_options(/W3)
else()
    add_compile_options(-Wall -Wextra -Wpedantic)
endif()
find_package(Curses REQUIRED)
add_executable(${PROJECT_NAME} main.cpp)
target_compile_definitions(${PROJECT_NAME} PRIVATE
    WATCH_PROJECT_VERSION="${PROJECT_VERSION}"
)
target_include_directories(${PROJECT_NAME} PRIVATE ${CURSES_INCLUDE_DIRS})
target_link_libraries(${PROJECT_NAME} PRIVATE ${CURSES_LIBRARIES})
