name: Build

on:
  push:
    tags:
      - "v*.*"

jobs:
  build:
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build --preset=vcpkg -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release

      - name: List build output
        shell: bash
        run: find ${{github.workspace}}/build -name "*.exe" -type f
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          path: ${{github.workspace}}/build/Release/*

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{github.workspace}}/build/Release/*

